# Generated by Django 4.1.1 on 2024-09-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potraviny',
            old_name='ovoce',
            new_name='cena',
        ),
        migrations.RenameField(
            model_name='potraviny',
            old_name='pecivo',
            new_name='potravina',
        ),
    ]
