# Generated by Django 4.1.1 on 2024-10-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_category_product_delete_potraviny'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotravinyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(to='viewer.potravinyfeatures'),
        ),
    ]
