# Generated by Django 4.1.1 on 2024-10-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
