# Generated by Django 4.1.1 on 2024-10-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_profile_remove_orderline_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
