# Generated by Django 4.1.1 on 2024-10-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.product')),
            ],
        ),
    ]
