# Generated by Django 4.1.1 on 2024-10-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='offer',
            new_name='product',
        ),
    ]
